"""
Create a sample test image for testing the image serving functionality.
Run this to create a test image in the generated_images folder.
"""

from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "generated_images"
OUTPUT_DIR.mkdir(exist_ok=True)


def create_sample_image():
    """Create a simple test image with text"""
    
    # Create a gradient background
    width, height = 600, 800
    image = Image.new('RGB', (width, height), color='white')
    draw = ImageDraw.Draw(image)
    
    # Create gradient background
    for y in range(height):
        # Gradient from pink to purple
        r = int(255 - (y / height) * 100)
        g = int(100 + (y / height) * 50)
        b = int(150 + (y / height) * 100)
        draw.rectangle([(0, y), (width, y + 1)], fill=(r, g, b))
    
    # Add text
    try:
        # Try to use a nice font, fallback to default
        font_large = ImageFont.truetype("arial.ttf", 60)
        font_small = ImageFont.truetype("arial.ttf", 30)
    except:
        font_large = ImageFont.load_default()
        font_small = ImageFont.load_default()
    
    # Add title
    title = "Fashion AI"
    draw.text((width // 2, height // 3), title, fill='white', 
              font=font_large, anchor='mm')
    
    # Add subtitle
    subtitle = "Sample Design"
    draw.text((width // 2, height // 2), subtitle, fill='white', 
              font=font_small, anchor='mm')
    
    # Add footer
    footer = "Generated by AI Service"
    draw.text((width // 2, height * 2 // 3), footer, fill='white', 
              font=font_small, anchor='mm')
    
    # Save the image
    output_path = OUTPUT_DIR / "design_sample.jpg"
    image.save(output_path, quality=95)
    
    print(f"✅ Sample image created: {output_path}")
    print(f"📷 Access at: http://localhost:8000/images/design_sample.jpg")
    return output_path


def create_placeholder_images(count=3):
    """Create multiple placeholder images with different colors"""
    
    colors = [
        ('#FF6B9D', '#C44569'),  # Pink
        ('#4ECDC4', '#1A535C'),  # Teal
        ('#FFD93D', '#F7B731'),  # Yellow
        ('#6C5CE7', '#A29BFE'),  # Purple
        ('#00B894', '#55EFC4'),  # Green
    ]
    
    created_images = []
    
    for i in range(min(count, len(colors))):
        width, height = 600, 800
        image = Image.new('RGB', (width, height))
        draw = ImageDraw.Draw(image)
        
        # Gradient with theme colors
        color1, color2 = colors[i]
        
        for y in range(height):
            # Simple gradient
            ratio = y / height
            # Convert hex to RGB
            r1, g1, b1 = int(color1[1:3], 16), int(color1[3:5], 16), int(color1[5:7], 16)
            r2, g2, b2 = int(color2[1:3], 16), int(color2[3:5], 16), int(color2[5:7], 16)
            
            r = int(r1 + (r2 - r1) * ratio)
            g = int(g1 + (g2 - g1) * ratio)
            b = int(b1 + (b2 - b1) * ratio)
            
            draw.rectangle([(0, y), (width, y + 1)], fill=(r, g, b))
        
        # Add text
        try:
            font_large = ImageFont.truetype("arial.ttf", 50)
            font_small = ImageFont.truetype("arial.ttf", 25)
        except:
            font_large = ImageFont.load_default()
            font_small = ImageFont.load_default()
        
        draw.text((width // 2, height // 2), f"Design #{i+1}", 
                  fill='white', font=font_large, anchor='mm')
        
        # Save
        filename = f"design_example_{i+1}.jpg"
        output_path = OUTPUT_DIR / filename
        image.save(output_path, quality=95)
        
        created_images.append({
            'filename': filename,
            'url': f"http://localhost:8000/images/{filename}"
        })
        
        print(f"✅ Created: {filename}")
    
    return created_images


if __name__ == "__main__":
    print("🎨 Creating sample images...\n")
    
    # Create main sample
    create_sample_image()
    print()
    
    # Create additional examples
    images = create_placeholder_images(3)
    
    print("\n" + "=" * 60)
    print("Sample Images Created Successfully!")
    print("=" * 60)
    print("\nYou can now:")
    print("1. Start the server: python app.py")
    print("2. Access images at: http://localhost:8000/images/")
    print("3. List all images: http://localhost:8000/images/list")
    print("\nExample URLs:")
    for img in images:
        print(f"  - {img['url']}")
